name: blinkit_clone_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  url_launcher: ^6.0.3
  firebase_core: ^3.8.0
  provider: ^6.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  country_picker: ^2.0.27
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cat/
    - assets/images/veg&fruits/
    - assets/images/juices/
    - assets/images/dairy/
    - assets/images/namkeen/
